openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Conference site server API'
  description: API

servers:
  - url: http://localhost:8080
    description: Сервис поисковой системы

paths:
  /user:
    get:
      summary: Поиск пользователя по логину
      parameters:
        - name: login
          description: Логин пользователя
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The user for the provided by login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: No user found for the provided login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
        - name: login
          description: Логин пользователя
          in: query
          required: true
          schema:
            type: string
        - name: first_name
          description: dsa
          in: query
          required: true
          schema:
            type: string
        - name: second_name
          description: Отчество пользователя
          in: query
          required: false
          schema:
            type: string
        - name: email
          description: E-Mail пользователя
          in: query
          required: true
          schema:
            type: string
        - name: gender
          description: Пол пользователя в формате (male/female)
          in: query
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search:
    get:
      summary: Поиск пользователя по маске имени и фамилии
      parameters:
        - name: first_name
          description: Маска имени пользователя
          in: query
          required: true
          schema:
            type: string
        - name: last_name
          description: Маска фамилии пользователя
          in: query
          required: true
          schema:
            type: string

      responses:
        '200':
          description: The users for the provided by mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    user:
      type: object
      required:
        - id
        - login
        - first_name
        - last_name
        - second_name
        - email
        - gender
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        login:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        second_name:
          type: string
        email:
          type: string
        gender:
          type: string
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []
